language: ruby

sudo: true

rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.7
  - 2.2.2
  - 2.2.3

gemfile:
  - Gemfile

notifications:
  email:
    - jacob.hammack@hammackj.com
  irc: "irc.freenode.org#risu"

before_install:
  - gem --version

after_success:
  - coveralls
