language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.3

gemfile:
  - Gemfile.ci

notifications:
  email:
    - jacob.hammack@hammackj.com
  irc: "irc.freenode.org#risu"

before_install:
  - gem --version
